### ISSUE TITLE
Merge/Update this extension with latest changes from vscode-angular-html

### ISSUE THREAD

**Issue by urielzen** [ghaschel/vscode-angular-ts#2]
Request to implement the latest changes from the html syntax extension (https://github.com/ghaschel/vscode-angular-html) into the inline syntax extension.

Is it possible to merge this extension into the `vscode-angular-html` extension? so only one has to be installed? also in order to manage color customization in only one extension?

**Comment by ghaschel** [comment]
I'll see what I can do

**Comment by ghaschel** [comment]
Well, I was able to get this integrated easily. But in order for this to work, this extension will depend on vscode-angular-html. The main grammar and customization will stay there, and this will only be a wrapper.  This will be great because it will completely remove duplication.

I'll have to update the docs, so even though this was a quick win, I'll take my time to update them. I'll release this probably at the end of the day or tomorrow

**Comment by urielzen** [comment]
You are the best. Thank you so much!

**Comment by ghaschel** [comment]
Done. Should be live at any minute. Let me know if it works for you, please :)

**Comment by urielzen** [comment]
It is working fine for me, thanks so much!
